apiVersion: v1
kind: Pod
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  containers:
  - image: grafana/grafana:9.4.3
    name: grafana
    env:
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
      - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        value: Admin
      - name: GF_AUTH_DISABLE_LOGIN_FORM
        value: "true"
      - name: GF_FEATURE_TOGGLES_ENABLE
        value: "traceqlEditor"
    ports:
      - containerPort: 3000
        name: http
    volumeMounts:
      - mountPath: /etc/grafana/provisioning/datasources
        name: datasource
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: datasource
      configMap:
        name: grafana-config

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
