apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  containers:
  - image: prom/prometheus:latest
    name: prometheus
    args:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=exemplar-storage"
    resources: {}
    ports:
      - containerPort: 9090
        name: http
    volumeMounts:
      - mountPath: /etc/prometheus
        name: config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: config
      configMap:
        name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
