apiVersion: v1
kind: Pod
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  containers:
  - image: grafana/tempo:latest
    name: tempo
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    ports:
      - containerPort: 14268
        name: jaeger
      - containerPort: 3200
        name: tempo
      - containerPort: 9095
        name: tempo-grpc
      - containerPort: 4317
        name: otlp-grpc
      - containerPort: 4318
        name: otlp-http
      - containerPort: 9411
        name: zipkin
    volumeMounts:
      - mountPath: /etc/tempo
        name: config
  volumes:
    - name: config
      configMap:
        name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 14268
      targetPort: 14268
    - protocol: TCP
      port: 3200
      targetPort: 3200
    - protocol: TCP
      port: 9095
      targetPort: 9095
    - protocol: TCP
      port: 4317
      targetPort: 4317
    - protocol: TCP
      port: 4318
      targetPort: 4318
    - protocol: TCP
      port: 9411
      targetPort: 9411